#
# This Kustomization puts all under
# resources specified files together.
#
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./ingress.yaml
- ./pvc.yaml
- ./service.yaml

images:
- name: uptime-kuma
  newName: louislam/uptime-kuma
  newTag: "1"


commonLabels:
  app.kubernetes.io/name: uptime-kuma
